### ISSUE TITLE
wrong DateTime Format by serialization

### ISSUE THREAD

**Issue by srobert0** [gturri/aXMLRPC#74] opened 2018-02-22 12:31 UTC
Hello

I currently use this library on my project.

I am facing a problem with the date format.
aXMLRPC uses the following format when writing a datetime:
`<dateTime.iso8601>20180222T130252</dateTime.iso8601>`

But the official format seems to be:
`<dateTime.iso8601>20180222T13:01:53</dateTime.iso8601>`
with ":" between the hours, minutes and seconds.

The Apache XML/RPC uses this format. 
According to https://en.wikipedia.org/wiki/XML-RPC it is also the right format.

By looking at the class DateTimeSerializer, the deserialization supports both formats (with and without ":") thanks to the use of Iso8601Deserializer.
The bug concerns only the serializer.

Is there any reason why you are using a time without ":"?

May we have a configuration parameter to choose between both formats by serializing?

Thanks
Samuel

**Comment by gturri** [comment] 2018-02-22 12:52
Hi,

According to both this wikipedia article and the xmlrpc spec (http://xmlrpc.scripting.com/spec.html) the dates should be written according to the ISO-8601 format.

The ISO-8601 format allows both hh:mm:ss and hhmmss (according to https://en.wikipedia.org/wiki/ISO_8601#Times (I'm afraid the ISO-8601 license doesn't allow me to share the original document))

So it seems to me that there's no bug in the serializer. (well, at least, _this_ is not a bug). I guess the proper fix should be on the server side, since it should accept any valid ISO-8601 format in order to be xmlrpc compliant. (If the server in running a JVM, using http://github.com/gturri/jISO8601 might be an option).

That being said, your suggestion to add a configuration parameter could let you move forward, and could be an acceptable solution.

I'm afraid I won't have time to work on adding such parameter, but if you submit a pull request, I'll gladly look at it. (If you do, please do include non regression tests)

**Comment by gturri** [comment] 2018-02-23 08:43
On 2nd though: just adding an option to add ":" in the time would be a bit clumsy, because the ISO-8601 actually offers much more flexibility in the acceptable formats (as can be seen for instance in the jISO8601 tests (in particular for the dates https://github.com/gturri/jISO8601/blob/master/src/test/java/fr/turri/jiso8601/TestDeserializeCalendarDates.java ; and for the times https://github.com/gturri/jISO8601/blob/master/src/test/java/fr/turri/jiso8601/TestDeserializeTimes.java).
It hence seems more relevant to me to close this issue. Feel free to re-open it if you don't share the opinion.

**Closed by gturri** 2018-02-23 08:43 UTC
Labels: Feature

**Comment by srobert0** [comment] 2018-02-25 16:45
Thanks for yougr feedback.
You are right the clients and servers have to support the whole flexibility of ISO-8601.
As I saw the time with ":" in all XML/RPC examples I thought it was a restriction to the standard. And I guess some other people do so as well.
In my case that would be a bug on the server side. But that is a third party application which I cannot change.

Perhaps we could add an option as a feature to set the default datetime format to be used by the serializer. The default value would remain the current one.

If I find the time I will propose a change.
