### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by flohmueller** [gturri/aXMLRPC#43] opened 2015-03-26 15:45 UTC
Hi there..

I stumbled across a nasty encoding issue that could only be solved by using the vm parameter `-Dfile.encoding=UTF-8`.

It seems your `SimpleXMLCreator` is a little liar when it comes to the xml encoding.. The value used in `"<?xml version=\"1.0\" encoding=\"UTF-8\"?>` is not necessarily the same when `de.timroes.axmlrpc.XMLRPCClient.Caller.call(String, Object[])` writes the xml to the http output stream.
Maybe you could replace 
  `OutputStreamWriter stream = new OutputStreamWriter(http.getOutputStream());`
by
  `OutputStreamWriter stream = new OutputStreamWriter(http.getOutputStream(), Charset.forName("UTF-8"));`
in [this line](https://github.com/timroes/aXMLRPC/blob/master/src/main/java/de/timroes/axmlrpc/XMLRPCClient.java#L652)?

**Comment by gturri** [comment] 2016-01-30 15:19
Hi,

if you're still interested in that bug, since you have the fix, could you please submit a pull request with both this fix, and consequent no reg test?

(Ideally, please submit the PR on https://github.com/gturri/aXMLRPC)

**Comment by flohmueller** [comment] 2016-02-12 06:52
Hey gturri, 
sry for taking so long.. 
unfortunately I have no idea what you mean by "no reg test". I understand it's got something to do with android compatibility..!? But currently I'm neither into android development nor doing builds/tests/whatever with gradle. :(
Sorry to let you down..

**Comment by Frettman** [comment] 2022-11-04 14:05
I'm also interested in having this fixed, especially since the fix - as shown - is quite trivial.

**Comment by Frettman** [comment] 2022-11-04 16:33
The problem is that `new OutputStreamWriter(http.getOutputStream())` uses the system's default encoding to write out the XML request. When the default encoding is _not_ `UTF-8` (like on Windows; at least until Java 18), this is in conflict with the static `<?xml version="1.0" encoding="UTF-8"?>` from the generated request.
I suppose the default encoding on Android is already UTF-8, so it's never been an issue there.
By explicitly setting the encoding like in `new OutputStreamWriter(http.getOutputStream(), StandardCharsets.UTF_8)`, this can be avoided. This would fix it for every platform where `UTF-8` isn't the default and change nothing for every platform where `UTF-8` already is the default.

**Comment by gturri** [comment] 2022-11-04 18:56
Thanks for this information.
The fix is merged.
I'll try to release an updated version soon

**Closed** 2022-11-04 18:55 UTC
Labels: Improvement

**Comment by gturri** [comment] 2022-11-04 21:25
The fix should be available in aXMLRPC v `1.12.1` that I just released.
However, I didn't do releases in a while and I encountered some weird error in the process. So even though I see that this version is available on maven central (https://central.sonatype.dev/artifact/fr.turri/aXMLRPC/1.12.1 ), I'm not 100% sure it was all successful.

Long story short:  @Frettman I would appreciate if you can check on your side that using `1.12.1` indeed fixes the issue you observe

**Comment by Frettman** [comment] 2022-11-04 21:27
Thanks a lot for the quick response and fix. Much appreciated :)

**Comment by Frettman** [comment] 2022-11-07 16:28
I can confirm that the release has indeed fixed the issue :)

**Comment by gturri** [comment] 2022-11-07 17:08
Cool! thanks for taking the time to test it
