### ISSUE TITLE
Empty dateTime.iso8601 causes exception

### ISSUE THREAD

**Issue by taranion** [gturri/aXMLRPC#75] opened 2018-03-06 15:11 UTC
Hi,

When parsing the following XMLRPC response, I get an exception indicating a parse error with the (second) dateTime.iso8601 element, which is empty.

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <methodResponse>
      <params>
        <param>
          <value>
            <struct>
              <member>
                <name>mac</name>
                <value>
                  <string>0080F0C8A505</string>
                </value>
              </member>
              <member>
                <name>url</name>
                <value>
                  <string>https://xsp1.bmcag.com/dms/Panasonic-KX-UT133-default/ConfigCommon.cfg</string>
                </value>
              </member>
              <member>
                <name>register_date</name>
                <value>
                  <dateTime.iso8601>2018-03-06T06:21:20Z</dateTime.iso8601>
                </value>
              </member>
              <member>
                <name>access_date</name>
                <value>
                  <dateTime.iso8601 />
                </value>
              </member>
              <member>
                <name>note</name>
                <value>
                  <string />
                </value>
              </member>
              <member>
                <name>profile</name>
                <value>
                  <string />
                </value>
              </member>
              <member>
                <name>model</name>
                <value>
                  <string>KX-UT113NE</string>
                </value>
              </member>
              <member>
                <name>version</name>
                <value>
                  <string />
                </value>
              </member>
            </struct>
          </value>
        </param>
      </params>
    </methodResponse>

The resulting exception:

    de.timroes.axmlrpc.XMLRPCException: Unable to parse given date.
        at de.timroes.axmlrpc.serializer.DateTimeSerializer.deserialize(DateTimeSerializer.java:30)
        at de.timroes.axmlrpc.serializer.DateTimeSerializer.deserialize(DateTimeSerializer.java:23)
        at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(SerializerHandler.java:130)
        at de.timroes.axmlrpc.serializer.StructSerializer.deserialize(StructSerializer.java:71)
        at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(SerializerHandler.java:130)
        at de.timroes.axmlrpc.ResponseParser.getReturnValueFromElement(ResponseParser.java:119)
        at de.timroes.axmlrpc.ResponseParser.parse(ResponseParser.java:71)
        at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:742)
        at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:462)
        at de.qsc.uranos.redirector.panasonic.PanasonicRedirector.getDeviceInfo(PanasonicRedirector.java:131)
        at de.qsc.uranos.redirector.panasonic.PanasonicRedirector.main(PanasonicRedirector.java:56)
    Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 4
        at java.lang.String.substring(String.java:1963)
        at fr.turri.jiso8601.Iso8601Deserializer.parseCalendarDateWithPrecisionGreaterThanYear(Iso8601Deserializer.java:116)
        at fr.turri.jiso8601.Iso8601Deserializer.parseCalendarDate(Iso8601Deserializer.java:101)
        at fr.turri.jiso8601.Iso8601Deserializer.buildCalendarWithDateOnly(Iso8601Deserializer.java:91)
        at fr.turri.jiso8601.Iso8601Deserializer.toCalendar(Iso8601Deserializer.java:17)
        at fr.turri.jiso8601.Iso8601Deserializer.toDate(Iso8601Deserializer.java:12)
        at de.timroes.axmlrpc.serializer.DateTimeSerializer.deserialize(DateTimeSerializer.java:28)
        ... 10 more

**Comment by gturri** [comment] 2018-03-06 15:36
Hi,

It seems to me that empty dateTimes aren't allowed according to the xmlrpc spec (http://xmlrpc.scripting.com/spec.html). It hence seems to me it's rather an issue with the server which shouldn't send this field. I'm hence closing this issue. Feel free to re-open it if you disagree with this conclusion.

Still, we might imagine adding a flag that would let the client support this kind of reply. I don't plan on working on it, but if a pull request that adds it (along with unit tests) is submitted, I'll look at it.

That being said, thanks for enclosing both the input which makes it possible to reproduce the issue, along with the stacktrace. It made it easy to understand what this issue is about. You could submit even more effective bug reports by paying attention to two additional details:
* you can use the `Preview` tab before posting: it would have made it possible to notice that the xmlrpc input wasn't being displayed at all (because github "eats" xml like tags. I'm the one who edited it to put it in a code block so that it displayed correctly).  
* since you noticed the exact part of the input which is causing the issue, it would have been awesome to come up with an even smaller (but still self contained) input (ie: a self sufficient 10 lines input would have be pretty cool compared to this 60 lines one). Also, it would have been awesome to indent it properly.

**Closed by gturri** 2018-03-06 15:36 UTC

**Comment by taranion** [comment] 2018-03-06 15:42
Okay, understood. I am not familiar with the XMLRPC details, so I trust you on this. Unfortunately I have no control over the server XMLRPC implementation - I just need to interwork with it.

Regarding the effective bug report: You were too fast. When I noticed how the XML and stack trace came out, it took me some time to learn how to correct that using markdown. It should be better readable now.

**Comment by gturri** [comment] 2018-03-06 16:03
Sorry for being too fast ;) (and thanks for enhancing the original post!)

If you think adding a flag to allow nullable input could help you move forward, feel free to submit a pull request. (if you have questions about how to do it, don't hesitate to ask)
