### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by aungmyint** [gturri/aXMLRPC#78] opened 2018-09-02 11:38 UTC
Records create from android to Odoo server using this library. This records save in database. But Api response exception (java.io.FileNotFoundException:   http://ip address: port/xmlrpc/2/object). Exception is sometimes.

**Comment by gturri** [comment] 2018-09-02 11:53
It would be awesome to have at least:
* a way to reproduce this issue (for instance your code)
* the stacktrace that goes with this exception
* the error log of the odoo server (if there are any)
* the output produced by your code when you use the flag `FLAGS_DEBUG`

Without this information there's no real way to understand this error you're experiencing.

**Comment by aungmyint** [comment] 2018-09-02 12:03
Thank your reply.

**Comment by aungmyint** [comment] 2018-09-24 15:46
Sale order creates with many items (50) using this library to odoo server. Sale order saves all items in odoo database but api response as exception. Exception is gate way timeout and status code is 504. How to solve this issue?

**Comment by gturri** [comment] 2018-09-24 16:13
If you have a timeout issue when you try to create a lot of items then it's tempting to suggest to create fewer items. Or to configure your server to have a longer timeout.

When the http code starts with a 5 it means it's a server error, so it would be more relevant to open a bug report on the project of the server.

I'm closing this issue since it seems unrelated to aXMLRPC.

If you believe you find another issue related to this piece of software, feel free to open another issue. But if you do, please, provide at least:
* a way to reproduce this issue (for instance your code, or even better, a minimal version of it)
* the stacktrace that goes with this exception
* the output produced by your code when you use the flag `FLAGS_DEBUG`

**Closed by gturri** 2018-09-24 16:13 UTC
