### ISSUE TITLE
No deserializer for Ex:Nil

### ISSUE THREAD

**Issue by drenda** [gturri/aXMLRPC#36] opened 2014-04-04 06:44 UTC
Hi,
I'm using this library using XMLRPCClient.FLAGS_DEFAULT_TYPE_STRING | XMLRPCClient.FLAGS_NIL flags but when the server send me a null value I've this exception on the client:
04-04 08:38:48.835  16314-16767﹕ de.timroes.axmlrpc.XMLRPCException: Error getting result from server.
            at de.timroes.axmlrpc.ResponseParser.parse(Unknown Source)
            at de.timroes.axmlrpc.XMLRPCClient$Caller.call(Unknown Source)
            at de.timroes.axmlrpc.XMLRPCClient$Caller.run(Unknown Source)
     Caused by: de.timroes.axmlrpc.XMLRPCException: No deserializer found for type 'ex:nil'.
            at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(Unknown Source)
            at de.timroes.axmlrpc.serializer.StructSerializer.deserialize(Unknown Source)
            at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(Unknown Source)
            at de.timroes.axmlrpc.serializer.StructSerializer.deserialize(Unknown Source)
            at de.timroes.axmlrpc.serializer.SerializerHandler.deserialize(Unknown Source)
            at de.timroes.axmlrpc.ResponseParser.getReturnValueFromElement(Unknown Source)
            at de.timroes.axmlrpc.ResponseParser.parse(Unknown Source)
            at de.timroes.axmlrpc.XMLRPCClient$Caller.call(Unknown Source)
            at de.timroes.axmlrpc.XMLRPCClient$Caller.run(Unknown Source)
il'.

There is a way to solve this?

Thanks!

**Comment by gturri** [comment] 2017-10-03 07:11
Closing because it seems the issue comes from the server, and because plans for 2.0.0 have been forsaken. (and the issue is more than 3y old anyway)

**Closed by gturri** 2017-10-03 07:11 UTC
